import React, { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ListTodo from '../components/ListTodo'
import AddTodo from '../components/AddTodo'
import { ITodo } from '../interfaces'
import { Todo } from '../models/todo'


export default function Home() {
  const initTodo = [
    new Todo({id: 1, name: 'Todo 1'}),
    new Todo({id: 2, name: 'Todo 2'}),
    new Todo({id: 3, name: 'Todo 3'})
  ]
  const [listTodo, setListTodo] = useState<ITodo[]>(initTodo);

  const handleAddTodo = (title: string) => {
    const todo: Todo = {
      id: Math.floor((Math.random()*1000) + 1),
      name: title
    }
    const newArr: Todo[] = [...listTodo, todo]
    setListTodo(newArr)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div className="add__todo">
          <AddTodo handleAddTodo={handleAddTodo} />
        </div>
        <div className="list__todo">
          <ListTodo items={listTodo} />
        </div>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
